# Generated by Django 4.2.11 on 2025-05-17 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnownPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('embedding', models.BinaryField()),
                ('photo', models.ImageField(upload_to='known_photos/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('camera_name', models.CharField(default='camera_a', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UnknownPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('embedding', models.BinaryField()),
                ('photo', models.ImageField(upload_to='unknown_photos/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('camera_name', models.CharField(default='camera_a', max_length=100)),
            ],
        ),
    ]
