# Generated by Django 4.2.11 on 2025-05-17 13:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonSighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('known_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.knownperson')),
                ('unknown_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.unknownperson')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
