# Generated by Django 4.2.11 on 2025-05-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_personsighting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unknownperson',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
