# Generated by Django 4.2.11 on 2025-05-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_unknownperson_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='personsighting',
            name='captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personsighting',
            name='latency',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
